

obj-$(CONFIG_SECO_COMMON_BOARD)      +=   board.o

obj-$(CONFIG_SECO_COMMON_USDHC)      +=   usdhc.o

obj-$(CONFIG_SECO_COMMON_RGMII)      +=   net_rgmii.o
obj-$(CONFIG_SECO_COMMON_RMII)       +=   net_rmii.o

obj-$(CONFIG_SECO_COMMON_PFUZE)      +=   pfuze.o

obj-$(CONFIG_SECO_COMMON_DISPLAY)    +=   display.o


